# fly.toml app configuration file generated for willcodefor-htmx on 2023-07-22T09:13:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "willcodefor-htmx"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"
